# Generated by Django 4.2.29 on 2026-03-24 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('predicted_class', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('plant_name', models.CharField(max_length=100)),
                ('disease_name', models.CharField(max_length=100)),
                ('is_healthy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
